COUCHBASE_CONN_STR = "<your-couchbase-cluster-url>"
COUCHBASE_USERNAME = "<your-username>"
COUCHBASE_PASSWORD = "<your-password>"
BUCKET_NAME = "travel-sample"
SCOPE_NAME = "inventory"
COLLECTION_NAME = "hotel"
