COUCHBASE_CONN_STR = "<your cluster string"
COUCHBASE_USERNAME = "you username"
COUCHBASE_PASSWORD = "your password"
BUCKET_NAME = "travel-sample"
SCOPE_NAME = "inventory"
COLLECTION_NAME = "hotel"
VECTOR_INDEX_NAME = "vector_idx"
VECTOR_FIELD = "description_embedding"
